FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod go.sum* ./
COPY vendor/ ./vendor/
COPY main.go ./
COPY internal/ ./internal/
RUN CGO_ENABLED=0 GOOS=linux go build -mod=vendor -o helios-backend ./main.go

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/helios-backend .

EXPOSE 8080
CMD ["./helios-backend"]
