FROM golang:1.22-alpine AS builder

WORKDIR /app

ENV GONOSUMDB=*

COPY go.mod go.sum ./
RUN go mod download

COPY main.go ./
COPY internal/ ./internal/
RUN CGO_ENABLED=0 GOOS=linux go build -o helios-backend ./main.go

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/helios-backend .

EXPOSE 8080
CMD ["./helios-backend"]
